# display_name: J2Lab
# lang_fw:
# labels: Go, Jira, Gitlab, Docker
# comment: 이 job은 j2lab CLI로 Jira 프로젝트를 GitLab 프로젝트로 마이그레이션합니다.
# comment:
# comment: 사전에 config.yaml 파일과 user.csv 파일을 구성해야 합니다.
# comment:
# comment: - `config.yaml` 환경 변수에는 Jira, GitLab 관련 정보가 들어있는 파일의 경로를 지정합니다.
# comment: - `user.csv` 환경 변수에는 Jira User Name과 GitLab User ID를 행 단위로 저장한 파일의 경로를 지정합니다.
# comment:
# comment: 샘플 파일을 생성하려면 아래 명령을 입력하세요.
# comment:
# comment: ``` bash
# comment: j2lab config new
# comment: ```

variables:
  CONFIG_PATH:
    value: "$CI_PROJECT_DIR/config.yaml"
    description: |
      Jira, GitLab 관련 정보가 들어있는 파일의 경로를 지정합니다.

      예시 config.yaml 파일을 생성하려면 아래 명령을 입력하세요.

      ``` bash
      j2lab config new
      ```
  USER_FILE:
    value: "$CI_PROJECT_DIR/user.csv"
    description: |
      Jira User Name과 GitLab User ID를 행 단위로 저장한 파일입니다.

      아래 예시와 같이 저장합니다.

      ``` text
      Jira User Name, GitLab User ID
      jeff, 123412
      ```
  GITLAB_TOKEN: #!
    value: ""
    description: GitLab 프로젝트에 접근하기 위한 엑세스 토큰입니다. 엑세스 토큰을 발급받으려면 [GitLab Docs](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token)를 참조하세요.
  JIRA_TOKEN: #!
    value: ""
    description: Jira 프로젝트에 접근하기 위한 엑세스 토큰입니다. 엑세스 토큰을 발급받으려면 [Jira Docs](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/)를 참조하세요.

j2lab:
  stage: test
  # image: j2lab job을 실행하는 데 필요한 Docker 이미지입니다.
  image: gitlab.com/infograb-public/j2lab:latest
  before_script:
    - |
      if [ ! -f $CONFIG_PATH ]; then  echo -e "
      ======================================================================
      \\e[1;91mError\\e[0m : config.yaml doesn't exist on $CONFIG_PATH
      ======================================================================
      "
        exit 1
      fi
    - |
      if [ ! -f $USER_FILE ]; then  echo -e "
      ======================================================================
      \\e[1;91mError\\e[0m : user.csv doesn't exist on $USER_FILE
      ======================================================================
      "
        exit 1
      fi
  script:
    - j2lab run -c $CONFIG_PATH -u $USER_PATH
