# usage
## git tag -a v0.1 -m "test relaese"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

stages:
  - release

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean

docker:dind:
  image: docker:24.0-cli
  stage: release
  services:
    - name: docker:20.10.12-dind
      command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_BUILDKIT: 1
    CONTEXT_PATH: $CI_PROJECT_DIR
    DOCKERFDIR_PATH: $CI_PROJECT_DIR
    DOCKERFILE_NAME: Dockerfile
  before_script:
    - |
      NOSLASH=$(echo "$CI_COMMIT_REF_NAME" | tr -s / - )
      SANITIZED=$(echo "$NOSLASH" | tr -cd '[[:alnum:]]._-')
      export CONTAINER_TAG=$SANITIZED
      export CONTAINER_REGISTRY_IMAGE_TAG="$CONTAINER_REGISTRY_IMAGE:$CONTAINER_TAG"
      echo $CONTAINER_REGISTRY_IMAGE_TAG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      docker build \
        -t $CONTAINER_REGISTRY_IMAGE_TAG \
        -t $CONTAINER_REGISTRY_IMAGE:latest .
    - docker push $CONTAINER_REGISTRY_IMAGE_TAG
